# Generated by Django 4.1 on 2022-09-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=10)),
                ('total_quantity', models.DecimalField(decimal_places=1, default=0.0, max_digits=9)),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('invoice_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('payment_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(default=0, max_length=1)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_code', models.CharField(max_length=6)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('attributes', models.CharField(max_length=1000)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('payment_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productmgt.accounts')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmgt.people')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, default=0.0, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmgt.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmgt.products')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productmgt.people'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productmgt.products'),
        ),
    ]
