# Generated by Django 4.1 on 2022-09-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0002_products_opening_stock_alter_accounts_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Amount',
            new_name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_items',
        ),
        migrations.AlterField(
            model_name='products',
            name='opening_stock',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('in stock', 'IN STOCK'), ('out of stock', 'OUT OF STOCK')], default=0, max_length=20),
        ),
    ]
