# Generated by Django 4.1 on 2022-09-22 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productmgt', '0004_rename_product_invoiceactivities_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productmgt.people'),
        ),
        migrations.AlterField(
            model_name='invoiceactivities',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productmgt.products'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productmgt.accounts'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
