# Generated by Django 4.1 on 2022-09-23 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productmgt', '0005_alter_invoice_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceactivities',
            name='invoice_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productmgt.invoice'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='user_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmgt.products')),
            ],
        ),
    ]
