# Generated by Django 4.1 on 2022-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0006_alter_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='opening_stock',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=9, verbose_name='Opening tock'),
        ),
    ]
