# Generated by Django 4.1 on 2022-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0007_alter_products_brand_alter_products_opening_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='opening_stock',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=9, null=True, verbose_name='Opening tock'),
        ),
    ]
