# Generated by Django 4.1 on 2022-09-26 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0008_alter_products_opening_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productmgt.people'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('in-stock', 'IN STOCK'), ('out-of-stock', 'OUT OF STOCK')], default='out-of-stock', max_length=20),
        ),
    ]
