# Generated by Django 4.1 on 2022-09-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0009_alter_payments_people_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('in-stock', 'IN STOCK'), ('out-of-stock', 'OUT OF STOCK'), ('disabled', 'Disable')], default='out-of-stock', max_length=20),
        ),
    ]
