# Generated by Django 4.1 on 2022-09-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0011_people_people_type_alter_products_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
