# Generated by Django 4.1 on 2022-09-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0012_people_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
