# Generated by Django 4.1 on 2022-10-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0013_people_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='invoiceactivities',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoiceactivities',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default='', max_digits=9),
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
