# Generated by Django 4.1 on 2022-10-30 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0014_alter_invoice_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceactivities',
            name='invoiced_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
