# Generated by Django 5.0.2 on 2024-02-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmgt', '0016_delete_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='payment_at',
            new_name='created_at',
        ),
    ]
