# Generated by Django 4.1 on 2022-11-15 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=9, null=True, verbose_name='Opening Balance')),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('expenses', 'Expenses')], default='bank', max_length=20)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=9, null=True, verbose_name='Current Balance')),
                ('opening_balance_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
