# Generated by Django 4.1 on 2022-11-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=90, max_digits=9, null=True, verbose_name='Current Balance'),
        ),
    ]
