# Generated by Django 4.1 on 2022-11-24 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productmgt', '0015_invoiceactivities_invoiced_at'),
        ('accounts', '0003_alter_accounts_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.CharField(choices=[('', 'Select account type'), ('bank', 'Bank'), ('expenses', 'Expenses')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='opening_balance_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Account_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
                ('payment_type', models.CharField(choices=[('', 'Select payment type'), ('bill', 'Payment to Vendor or Supplier'), ('sales', 'Payment from customer')], default='', max_length=50)),
                ('payment_at', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=250, null=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('applied_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productmgt.people')),
                ('form_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='accounts.accounts')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='accounts.accounts')),
            ],
        ),
    ]
