# Generated by Django 4.1 on 2022-11-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_account_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_activities',
            name='form_account',
        ),
        migrations.AddField(
            model_name='account_activities',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='accounts.accounts'),
        ),
        migrations.AlterField(
            model_name='account_activities',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account_activities',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='accounts.accounts'),
        ),
    ]
