# Generated by Django 4.1 on 2022-11-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_activities_form_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activities',
            name='payment_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
