# Generated by Django 5.0.2 on 2024-02-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_activities_payment_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_activities',
            old_name='payment_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='payment_at',
            new_name='created_at',
        ),
    ]
